package com.example.whatsapp_chat_assistant

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder
import android.util.Log
import androidx.core.app.NotificationCompat
import kotlinx.coroutines.*
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import java.io.File
import android.os.Binder

class LlamaInferenceService : Service() {
    private val TAG = "LlamaInferenceService"
    private var modelPointer: Long = 0L
    private val CHANNEL_ID = "LlamaInferenceChannel"
    private val serviceScope = CoroutineScope(Dispatchers.IO + SupervisorJob())
    private val inferenceMutex = Mutex()

    inner class LocalBinder : Binder() {
        fun getService(): LlamaInferenceService = this@LlamaInferenceService
    }

    private val binder = LocalBinder()

    override fun onCreate() {
        super.onCreate()
        Log.d(TAG, "onCreate")
        createNotificationChannel()
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        Log.d(TAG, "onStartCommand")
        val notification = NotificationCompat.Builder(this, CHANNEL_ID)
            .setContentTitle("Chat Assistant Active")
            .setContentText("Local AI engine is ready in the background")
            .setSmallIcon(R.drawable.ic_notification_circle) // Use your own icon
            .build()

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            startForeground(1, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE)
        } else {
            startForeground(1, notification)
        }

        // 3. Safe model loading using Coroutines
        serviceScope.launch {
            val modelFile = File(filesDir, "hinglish-qwen-3b-unsloth-Q4_K_M.gguf")
            Log.d(TAG, "Loading model from: ${modelFile.absolutePath}, exists: ${modelFile.exists()}")
            if (modelFile.exists()) {
                inferenceMutex.withLock {
                    if (modelPointer == 0L) {
                        Log.d(TAG, "Calling LlamaBridge.loadModel...")
                        modelPointer = LlamaBridge.loadModel(modelFile.absolutePath)
                        Log.d(TAG, "Model loaded, pointer: $modelPointer")
                    } else {
                        Log.d(TAG, "Model already loaded, pointer: $modelPointer")
                    }
                }
            } else {
                Log.e(TAG, "Model file NOT found at ${modelFile.absolutePath}")
            }
        }

        return START_STICKY
    }


    // 4. Expose a safe generation function for your broadcast receivers/listeners to call
    // 4. Expose a safe generation function that accumulates the token stream
    suspend fun generateResponseSafely(prompt: String): String {
        Log.d(TAG, "generateResponseSafely called with prompt length: ${prompt.length}")
        return inferenceMutex.withLock {
            if (modelPointer != 0L) {
                val responseBuilder = StringBuilder()

                Log.d(TAG, "Starting inference via LlamaBridge...")
                // Pass all 3 arguments: pointer, prompt, and the streaming lambda callback
                LlamaBridge.generateResponse(modelPointer, prompt) { token ->
                    // This block fires every single time a new token is generated by llama.cpp
                    responseBuilder.append(token)
                }

                val fullResponse = responseBuilder.toString()
                Log.d(TAG, "Inference complete. Response length: ${fullResponse.length}")
                fullResponse
            } else {
                Log.e(TAG, "generateResponseSafely: Model not loaded")
                "Error: Model not loaded."
            }
        }
    }



    override fun onDestroy() {
        Log.d(TAG, "onDestroy")
        super.onDestroy()
        // 5. Cancel coroutines and free C++ memory safely
        serviceScope.cancel()
        if (modelPointer != 0L) {
            Log.d(TAG, "Freeing model pointer: $modelPointer")
            LlamaBridge.freeModel(modelPointer)
            modelPointer = 0L
        }
    }

    override fun onBind(intent: Intent): IBinder {
        return binder
    }

    private fun createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                CHANNEL_ID,
                "LLM Inference Service",
                NotificationManager.IMPORTANCE_LOW
            )
            getSystemService(NotificationManager::class.java).createNotificationChannel(channel)
        }
    }
}